# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: E-Commerce
  licenses: Apache-2.0
  images: |
    - name: apache-exporter
      image: docker.io/bitnami/apache-exporter:1.0.2-debian-11-r10
    - name: elasticsearch
      image: docker.io/bitnami/elasticsearch:7.17.14-debian-11-r1
    - name: magento
      image: docker.io/bitnami/magento:2.4.6-debian-11-r114
    - name: mariadb
      image: docker.io/bitnami/mariadb:10.6.15-debian-11-r49
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r90
apiVersion: v2
appVersion: 2.4.6
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - magento-database
  version: 14.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Magento is a powerful open source e-commerce platform. With easy customizations and rich features, it allows retailers to grow their online businesses in a cost-effective way.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/magento/img/magento-stack-220x234.png
keywords:
- magento
- e-commerce
- http
- web
- php
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: magento
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/magento
version: 24.0.1
